export const IMAGE = {
  logo: require('../assets/image/logo.png'),
  login_card_bg: require('../assets/login_card_bg.png'),
  app_background: require('../assets/image/background.png'),
  SplashImage: require('../assets/splash.png'),
  back_arrow: require('../assets/back_arrow.png'),
  signup_bg: require('../assets/signup_bg.png'),
  congratulation: require('../assets/congratulation.png'),
  banner_bg: require('../assets/banner_bg.png'),
  card2: require('../assets/card2.png'),
  card3: require('../assets/card3.png'),
  card1: require('../assets/card1.png'),
  live_auction_pic: require('../assets/live_auction_pic.png'),
  live_auction_bg: require('../assets/live_auction_bg.png'),
  upload_image: require('../assets/upload_image.png'),

  banner: require('../assets/banner_bg.png'),


  no_data: require('../assets/new/no_data.png'),
  header_profile: require('../assets/new/user-square.png'),
  header_noti: require('../assets/new/notification.png'),
  dashboard_profile_bg: require('../assets/new/dashboard_profile_bg.png'),
  verify_icon: require('../assets/new/verify.png'),
  call_calling: require('../assets/new/call-calling.png'),
  clients_icon: require('../assets/new/clients_icon.png'),
  case_icon: require('../assets/new/case_icon.png'),
  judgement_icon: require('../assets/new/judgement_icon.png'),
  enquery_icon: require('../assets/new/enquery_icon.png'),
  causelist_icon: require('../assets/new/causelist_icon.png'),
  appoinment_icon: require('../assets/new/appoinment_icon.png'),
  displayboard_bg: require('../assets/new/displayboard_bg.png'),
  receipt: require('../assets/new/receipt-2.png'),
  card_receive: require('../assets/new/card-receive.png'),
  trash: require('../assets/new/trash.png'),
  call_calling_one: require('../assets/new/call-calling_one.png'),
  import: require('../assets/new/import.png'),
  
};
export const COLORS = {
  STATUS_BAR: '#0b93f6',
  STATUS_BAR_login: 'rgba(0, 45, 82, 1)',
  WHITE: '#FFF',
  PINK: '#EC53B0',
  ASH: '#CCCCCC',
  WhiteBg:'#fff',
  themeColor: 'rgba(0, 45, 82, 1)',
};
export const ICON = {
  logo: require('../assets/icon/logo.png'),
  mobile: require('../assets/icon/mobile.png'),
  password: require('../assets/icon/password.png'),
  eye_on: require('../assets/icon/eye_on.png'),
  eye_of: require('../assets/icon/eye_of.png'),
  login: require('../assets/icon/login.png'),
  user: require('../assets/icon/user.png'),
  organization: require('../assets/icon/organization.png'),
  right_arrow: require('../assets/icon/right_arrow.png'),
  email: require('../assets/icon/email.png'),
  verified: require('../assets/icon/verified.png'),
  noti: require('../assets/icon/noti.png'),
  notification: require('../assets/icon/notification.png'),
  profile: require('../assets/icon/profile.png'),
  menu: require('../assets/icon/menu.png'),
  auction_end: require('../assets/icon/auction_end.png'),
  auction_start: require('../assets/icon/auction_start.png'),
  up_arrow: require('../assets/icon/up_arrow.png'),
  down_arrow: require('../assets/icon/down_arrow.png'),
  tab3: require('../assets/icon/tab3.png'),
  tab4: require('../assets/icon/tab4.png'),
  tab2: require('../assets/icon/tab2.png'),
  tab1: require('../assets/icon/tab1.png'),
  add: require('../assets/icon/add.png'),
  more: require('../assets/icon/more.png'),
  edit: require('../assets/icon/edit.png'),
  delete: require('../assets/icon/delete.png'),
  filter: require('../assets/icon/filter.png'),
  search: require('../assets/icon/search.png'),
  noti_page_image_icon: require('../assets/icon/noti_page_image_icon.png'),
  select_box_icon: require('../assets/icon/select_box_icon.png'),
  $: require('../assets/icon/$.png'),
  time: require('../assets/icon/time.png'),
  date: require('../assets/icon/date.png'),
  congo: require('../assets/icon/congo.png'),
  logout: require('../assets/icon/logout.png'),
  bid_profile_image: require('../assets/icon/bid_profile_image.png'),
  win: require('../assets/icon/win.png'),
  edit_input: require('../assets/icon/edit_input.png'),
  camera: require('../assets/icon/camera.png'),
  faq: require('../assets/icon/faq.png'),
  opposite_selection: require('../assets/icon/opposite_selection.png'),
  key: require('../assets/icon/key.png'),
  calender: require('../assets/icon/calender.png'),
  location: require('../assets/icon/location.png'),
  case_history: require('../assets/icon/case_history.png'),
  profile_image: require('../assets/icon/profile_image.png'),
  judgement: require('../assets/icon/judgement.png'),
  home: require('../assets/icon/home.png'),
  chat: require('../assets/icon/chat.png'),
  wave: require('../assets/icon/wave.png'),
  back: require('../assets/icon/back.png'),
  about: require('../assets/icon/about.png'),
  address: require('../assets/icon/address.png'),
  charges: require('../assets/icon/charges.png'),
  id_card: require('../assets/icon/id_card.png'),
  next: require('../assets/icon/next.png'),
  upload: require('../assets/icon/upload.png'),
  upload_background: require('../assets/icon/upload_background.png'),
  live_board: require('../assets/icon/live_board.png'),
  request: require('../assets/icon/request.png'),
  india: require('../assets/icon/india.png'),
  edit_data: require('../assets/icon/edit_data.png'),
  bar_association: require('../assets/icon/bar_association.png'),
  practice_area: require('../assets/icon/practice_area.png'),
  specialised: require('../assets/icon/specialised.png'),
  client: require('../assets/icon/client.png'),
  case: require('../assets/icon/case.png'),
  more_option: require('../assets/icon/more_option.png'),
  call: require('../assets/icon/phone.png'),
  add_client: require('../assets/icon/add_client.png'),
  member: require('../assets/icon/member.png'),
  close_circle: require('../assets/icon/close_circle.png'),
  pdf: require('../assets/icon/pdf.png'),
  doc: require('../assets/icon/doc.png'),
  img: require('../assets/icon/img.png'),
 
};
